/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import login.Home_Page;
import login.employee;
/**
 *
 * @author hp
 */
public class add_employee extends javax.swing.JFrame {

    /**
     * Creates new form add_employee
     */
    public add_employee() {
        initComponents();
           
         Connect();
         auto_id();

    }

 Connection con;
PreparedStatement pst;
ResultSet rs;
public void Connect()
    {
        try {
           Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/super_shop", "root","");
        }
        catch (Exception e)
        {
        }
    }
    

public void auto_id()
    {
        try {
          
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(id) FROM employee_details");
            rs.next();
            rs.getString("MAX(id)");
            if (rs.getString("MAX(id)") == null) {
                id.setText("01");    
            } else {
                int c_id = rs.getInt(1);
                c_id++;
              id.setText(Integer.toString( c_id));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        reset = new javax.swing.JButton();
        addnew = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        salary = new javax.swing.JTextField();
        post = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        id2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(255, 153, 153));
        getContentPane().setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/teamc.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13);
        jLabel13.setBounds(1240, 910, 60, 80);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Designed By Team c");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(1100, 950, 140, 20);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(null);

        reset.setBackground(new java.awt.Color(0, 51, 102));
        reset.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/Refresh-icon (1).png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(520, 422, 97, 33);

        addnew.setBackground(new java.awt.Color(51, 153, 0));
        addnew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addnew.setForeground(new java.awt.Color(255, 255, 255));
        addnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/Button-Add-icon (1).png"))); // NOI18N
        addnew.setText("Add ");
        addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewActionPerformed(evt);
            }
        });
        jPanel1.add(addnew);
        addnew.setBounds(635, 422, 89, 33);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel3.setText("Enter ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 140, 170, 70);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("Information");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 270, 300, 56);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setText("Employee ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 210, 220, 56);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Employee Id :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(300, 60, 130, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Full Name :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(320, 120, 100, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Phone No:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(330, 180, 92, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Address: ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 240, 85, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("post: ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 300, 50, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Salary: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(360, 360, 67, 30);

        salary.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salaryActionPerformed(evt);
            }
        });
        jPanel1.add(salary);
        salary.setBounds(440, 360, 288, 30);

        post.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel1.add(post);
        post.setBounds(440, 300, 288, 30);

        address.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel1.add(address);
        address.setBounds(440, 240, 288, 30);

        id.setBackground(new java.awt.Color(51, 51, 51));
        id.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        id.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.add(id);
        id.setBounds(440, 60, 288, 30);

        name.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel1.add(name);
        name.setBounds(440, 120, 288, 30);

        phone.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel1.add(phone);
        phone.setBounds(440, 180, 288, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(130, 130, 760, 520);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));

        delete.setBackground(new java.awt.Color(255, 0, 51));
        delete.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/delete-icon.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        id2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Id to delete An Employee : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(id2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(delete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(130, 710, 770, 100);

        id1.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        getContentPane().add(id1);
        id1.setBounds(486, 158, 288, 30);

        jPanel3.setBackground(new java.awt.Color(30, 30, 30));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Edit Employee Details");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(2048, 28, 500, 64);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/BUBT.png"))); // NOI18N
        jLabel15.setText("jLabel6");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15);
        jLabel15.setBounds(1790, 10, 120, 150);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/edit employee.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(12, 13, 2029, 1129);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 2030, 1080);

        jMenuBar1.setBackground(new java.awt.Color(153, 51, 0));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(0, 3));
        jMenuBar1.setName("back"); // NOI18N

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setForeground(new java.awt.Color(204, 51, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/back.png"))); // NOI18N
        jMenu3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/home_1.png"))); // NOI18N
        jMenu4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setForeground(new java.awt.Color(204, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/rsz_1exittttt.png"))); // NOI18N
        jMenu2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed

String dlt;
dlt  = id2.getText();
try {
pst = con.prepareStatement("delete from employee_details where id =?");
            pst.setString(1, dlt);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Delete!!!!!");

         id2.setText("");
name.setText("");
phone.setText("");
address.setText("");
post.setText("");
salary.setText("");
           name.requestFocus();
}
catch (SQLException e1) {
e1.printStackTrace();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    

    
    private void addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewActionPerformed

String c_id,c_name,c_phone,c_address,c_post,c_salary;
c_id = id.getText();
c_name = name.getText();
c_phone =phone.getText();
c_address=address.getText();
c_post=post.getText();
c_salary=salary.getText();

try {
pst = con.prepareStatement("insert into employee_details(id,name,phone_no,address,post,salary)values(?,?,?,?,?,?)");
pst.setString(1, c_id);
pst.setString(2, c_name);
pst.setString(3, c_phone);
pst.setString(4,c_address);
pst.setString(5,c_post);
pst.setString(6,c_salary);
pst.executeUpdate();
JOptionPane.showMessageDialog(null, "Record Addedddd!!!!!");
auto_id();
//id.setText("");
name.setText("");
phone.setText("");
address.setText("");
post.setText("");
salary.setText("");
name.requestFocus();
   }
 
catch (SQLException e1)
        {
e1.printStackTrace();
}


        // TODO add your handling code here:
    }//GEN-LAST:event_addnewActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
       
        name.setText(null);
        phone.setText(null);
        address.setText(null);
        post.setText(null);
        salary.setText(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed

    private void salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salaryActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked

        Home_Page info = new  Home_Page();
         info.setBounds(1,1,2000,1080);
        info.setVisible(true);
         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
      

        employee info = new employee();
         info.setBounds(1,1,2000,1080);
        info.setVisible(true);
 dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed


        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked

        Group_info  info = new Group_info ();
        info.setBounds(1,1,2000,1080);
        info.setVisible(true);
         dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog (null, "Are you sure to exit ?","WARNING", dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if(dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
    Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://bubt.edu.bd"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}
        // TODO add your handling code here:
                 // TODO add your handling code here:
    }//GEN-LAST:event_jLabel15MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnew;
    private javax.swing.JTextField address;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id1;
    private javax.swing.JTextField id2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField post;
    private javax.swing.JButton reset;
    private javax.swing.JTextField salary;
    // End of variables declaration//GEN-END:variables
}
