/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import login.customer;
/**
 *
 * @author hp
 */
public class edit_customer extends javax.swing.JFrame {

    /**
     * Creates new form edit_customer
     */
    public edit_customer() {
        initComponents();
        
         Connect();
         auto_id();
    }

 Connection con;
PreparedStatement pst;
ResultSet rs;
public void Connect()
    {
        try {
           Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/super_shop", "root","");
        }
        catch (Exception e)
        {
        }
    }


public void auto_id()
    {
        try {
          
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(id) FROM customer_details");
            rs.next();
            rs.getString("MAX(id)");
            if (rs.getString("MAX(id)") == null) {
                id.setText("01");    
            } else {
                int c_id = rs.getInt(1);
                c_id++;
              id.setText(Integer.toString( c_id));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reset = new javax.swing.JButton();
        addnew = new javax.swing.JButton();
        address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id2 = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel3.setText("Enter ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 80, 170, 70);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setText("Customer");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 150, 220, 56);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("Information");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 210, 300, 56);

        reset.setBackground(new java.awt.Color(0, 51, 102));
        reset.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        reset.setForeground(new java.awt.Color(255, 255, 255));
        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/Refresh-icon (1).png"))); // NOI18N
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel1.add(reset);
        reset.setBounds(530, 310, 100, 40);

        addnew.setBackground(new java.awt.Color(0, 102, 0));
        addnew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addnew.setForeground(new java.awt.Color(255, 255, 255));
        addnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/Button-Add-icon (1).png"))); // NOI18N
        addnew.setText("Add");
        addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewActionPerformed(evt);
            }
        });
        jPanel1.add(addnew);
        addnew.setBounds(650, 310, 90, 40);

        address.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel1.add(address);
        address.setBounds(450, 260, 288, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Address : ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 260, 90, 30);

        phone.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel1.add(phone);
        phone.setBounds(450, 190, 288, 30);

        name.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(450, 120, 288, 30);

        id.setBackground(new java.awt.Color(0, 0, 0));
        id.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(id);
        id.setBounds(450, 70, 288, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Phone No:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(340, 190, 92, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Full Name :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(340, 130, 100, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Id :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(400, 70, 28, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(60, 100, 770, 390);

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter Id to delete An Employee : ");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 40, 433, 35);

        id2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jPanel2.add(id2);
        id2.setBounds(470, 40, 151, 30);

        delete.setBackground(new java.awt.Color(153, 0, 0));
        delete.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/delete-icon.png"))); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(640, 40, 115, 33);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(60, 570, 780, 110);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/BUBT.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1770, 10, 120, 150);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/teamc.png"))); // NOI18N
        jLabel9.setText("jLabel3");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1160, 910, 53, 70);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Designed By Team c");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(1000, 940, 140, 16);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/custom.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -30, 2600, 1070);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 0));

        jMenu5.setBackground(new java.awt.Color(255, 255, 255));
        jMenu5.setForeground(new java.awt.Color(204, 51, 0));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/back.png"))); // NOI18N
        jMenu5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu4.setBackground(new java.awt.Color(255, 255, 255));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/home_1.png"))); // NOI18N
        jMenu4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setForeground(new java.awt.Color(204, 51, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/rsz_1exittttt.png"))); // NOI18N
        jMenu3.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewActionPerformed
    
String c_id,c_name,c_phone,c_address;
c_id = id.getText();
c_name = name.getText();
c_phone =phone.getText();
c_address=address.getText();
try {
pst = con.prepareStatement("insert into customer_details(id,name,phone_no,address)values(?,?,?,?)");
pst.setString(1, c_id);
pst.setString(2, c_name);
pst.setString(3, c_phone);
pst.setString(4,c_address);
pst.executeUpdate();
JOptionPane.showMessageDialog(null, "Record Addedddd!!!!!");
auto_id();
name.setText("");
phone.setText("");
address.setText("");
name.requestFocus();
   }
 
catch (SQLException e1)
        {
e1.printStackTrace();
}


        // TODO add your handling code here:
    }//GEN-LAST:event_addnewActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        id.setText(null);
        name.setText(null);
        phone.setText(null);
        address.setText(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_resetActionPerformed
    
    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
  
String dlt;
dlt  = id2.getText();
try {
pst = con.prepareStatement("delete from customer_details where id =?");
            pst.setString(1, dlt);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Record Delete!!!!!");
      
          
         id2.setText("");
name.setText("");
phone.setText("");
address.setText("");
           name.requestFocus();
}
 
            catch (SQLException e1) {
e1.printStackTrace();
}        


// TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked

        Home_Page info = new  Home_Page();
                 info.setBounds(1,1,2000,1080);
        
        info.setVisible(true);
         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog (null, "Are you sure to exit ?","WARNING", dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if(dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked


        customer info = new customer();
        info.setBounds(1,1,2000,1080);
        info.setVisible(true);
 dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked

        Group_info info = new Group_info();
        info.setBounds(1, 1, 2000, 1080);
        info.setVisible(true);
         dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
  Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://bubt.edu.bd"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnew;
    private javax.swing.JTextField address;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JButton reset;
    // End of variables declaration//GEN-END:variables
}
