/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class Group_info extends javax.swing.JFrame {

    /**
     * Creates new form Group_info
     */
    public Group_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.textHighlight);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(204, 204, 255));
        setSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(null);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/user.png"))); // NOI18N
        jLabel12.setText(" Md Shahadat Hossen Shuvo ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(230, 310, 560, 43);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/id-card.png"))); // NOI18N
        jLabel7.setText(" 19202103067");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(230, 370, 320, 29);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/gmail-48.png"))); // NOI18N
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel21);
        jLabel21.setBounds(540, 460, 50, 60);

        jLabel25.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/contacts-48.png"))); // NOI18N
        jLabel25.setText(" Contact");
        getContentPane().add(jLabel25);
        jLabel25.setBounds(230, 470, 200, 48);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/instagram-48.png"))); // NOI18N
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24);
        jLabel24.setBounds(480, 460, 50, 60);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/facebook-48.png"))); // NOI18N
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(420, 460, 50, 60);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/mail_1.png"))); // NOI18N
        jLabel13.setText(" shahadat@ieee.org");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(230, 410, 460, 50);

        jLabel27.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/contacts-48.png"))); // NOI18N
        jLabel27.setText(" Contact");
        getContentPane().add(jLabel27);
        jLabel27.setBounds(1090, 490, 200, 48);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/facebook-48.png"))); // NOI18N
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel28);
        jLabel28.setBounds(1280, 480, 50, 60);

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/instagram-48.png"))); // NOI18N
        jLabel29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel29MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel29);
        jLabel29.setBounds(1340, 480, 50, 60);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/gmail-48.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel30);
        jLabel30.setBounds(1400, 480, 50, 60);

        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(220, 300, 630, 230);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(226, 141, 13));
        jLabel1.setText("Team C");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(860, 130, 328, 102);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(0, 0, 0, 0);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/mail_1.png"))); // NOI18N
        jLabel14.setText(" mahabubshakil1138@gmail.com");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(230, 840, 620, 50);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/user.png"))); // NOI18N
        jLabel3.setText(" Mahabub Mohammod Shakil");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 730, 550, 50);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/id-card.png"))); // NOI18N
        jLabel5.setText(" 19202103048");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 790, 280, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/medium.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(750, 70, 130, 180);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/mail_1.png"))); // NOI18N
        jLabel6.setText(" foridayeasmin2000@gmail.com");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1090, 440, 610, 40);

        jLabel31.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/contacts-48.png"))); // NOI18N
        jLabel31.setText(" Contact");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(230, 890, 200, 48);

        jLabel35.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/contacts-48.png"))); // NOI18N
        jLabel35.setText(" Contact");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(1110, 890, 200, 48);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/facebook-48.png"))); // NOI18N
        jLabel36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel36MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel36);
        jLabel36.setBounds(1300, 880, 50, 60);

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/instagram-48.png"))); // NOI18N
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel37);
        jLabel37.setBounds(1360, 880, 50, 60);

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/gmail-48.png"))); // NOI18N
        jLabel38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel38MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel38);
        jLabel38.setBounds(1420, 880, 50, 60);

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/facebook-48.png"))); // NOI18N
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel32);
        jLabel32.setBounds(420, 880, 50, 60);

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/instagram-48.png"))); // NOI18N
        jLabel33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel33MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel33);
        jLabel33.setBounds(480, 880, 50, 60);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/gmail-48.png"))); // NOI18N
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel34MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel34);
        jLabel34.setBounds(540, 880, 50, 60);

        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel19);
        jLabel19.setBounds(220, 710, 630, 230);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/id-card.png"))); // NOI18N
        jLabel8.setText("19202103041");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1100, 380, 320, 43);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/user.png"))); // NOI18N
        jLabel2.setText("Forida Yeasmin Sweety");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1100, 320, 460, 50);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/user.png"))); // NOI18N
        jLabel4.setText(" Tasnim Alamgir Athoye ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1110, 720, 500, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/mail_1.png"))); // NOI18N
        jLabel11.setText(" athoyehbk@gmail.com");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(1110, 830, 500, 50);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/id-card.png"))); // NOI18N
        jLabel9.setText(" 19202103522");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(1110, 780, 370, 30);

        jLabel18.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        getContentPane().add(jLabel18);
        jLabel18.setBounds(1090, 710, 620, 230);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/BUBT.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(1710, 10, 120, 140);

        jLabel17.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel17);
        jLabel17.setBounds(1080, 310, 630, 230);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/team bg.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, 0, 1930, 1080);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/team bg.png"))); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(0, 0, 1930, 1080);

        jMenuBar1.setBackground(new java.awt.Color(0, 51, 102));
        jMenuBar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuBar1MouseClicked(evt);
            }
        });

        jMenu4.setBackground(new java.awt.Color(0, 0, 0));
        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/home_1.png"))); // NOI18N
        jMenu4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu3.setBackground(new java.awt.Color(255, 255, 255));
        jMenu3.setForeground(new java.awt.Color(255, 51, 51));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/rsz_1exittttt.png"))); // NOI18N
        jMenu3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked

        Home_Page info = new  Home_Page();
        info.setBounds(1,1,2000,1080);
        info.setVisible(true);
         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog (null, "Are you sure to exit ?","WARNING", dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if(dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://bubt.edu.bd"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://mail.google.com/mail/u/0/#inbox?compose=GTvVlcRzDfnTJDsflDNQbJRLbVCRzTBZldkkBrPkGJBgTzgGkPsQzbtgJjnpwQxQcPvjpMzVVFPdL"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel21MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
   Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.instagram.com/md_shahadat_hossen_shuvo"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
 Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.facebook.com/md.shahadat.hossen.shuvo.s"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel23MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
    Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.facebook.com/forida.yeasmin.37625"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel29MouseClicked
    Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.instagram.com"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel29MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
    Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://mail.google.com/mail/u/0/#inbox?compose=DmwnWrRnZNGpXtnnHmPjsrZqvxDCBWqPcbgdhlLpRfjMGTPfNMMhCThHLVZSXtkJjnCWkWCfFvwL"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel32MouseClicked
   Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.facebook.com/Mahabubmohammedshakil"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel32MouseClicked

    private void jLabel33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel33MouseClicked
   Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.instagram.com/mahabub_mohammed_shakil"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33MouseClicked

    private void jLabel34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseClicked
   Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://mail.google.com/mail/u/0/#inbox?compose=GTvVlcSGLCBzLklRVfclXztSRpgMlCGxPtJWbTMPpsvWWCDhzspwXMHqPvjZZZzlDtrRVDNBfQDnD"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}     // TODO add your handling code here:
    }//GEN-LAST:event_jLabel34MouseClicked

    private void jLabel36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel36MouseClicked
    Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.facebook.com/profile.php?id=100011426479584"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}    // TODO add your handling code here:
    }//GEN-LAST:event_jLabel36MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
  Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://www.instagram.com/_ta_athoye_"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{} // TODO add your handling code here:
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel38MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel38MouseClicked
    Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://mail.google.com/mail/u/0/#inbox?compose=DmwnWsdDzHrMSZxTvvrbcCfVPRMkdTqnvHWVJckhjNmQJSPSKvHmGnsbzhkcfVbFNmpGzvKwJJcb"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}     
       

// TODO add your handling code here:
    }//GEN-LAST:event_jLabel38MouseClicked

    private void jMenuBar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuBar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuBar1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Group_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Group_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Group_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Group_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Group_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
