package login;
//import javax.swing.*;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import login.employee;
import login.Add_Product;
import login.customer;
import login.purchase;
import login.Group_info;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class Home_Page extends javax.swing.JFrame {

    /**
     * Creates new form Home_Page
     */
    public Home_Page() {
        initComponents();
        showdate();
        show_time();
    }

    void showdate() {

        Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("dd-MM-yyyy");
        jdate.setText(f.format(d));

    }

    void show_time() {
 new Timer(0, new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent ae) {
             Date d = new Date();
        SimpleDateFormat f = new SimpleDateFormat("hh:mm:ss");
        jtime.setText(f.format(d));
        }
    
    
   
    
    
    
    }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jdate = new javax.swing.JLabel();
        jtime = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Purchase = new javax.swing.JButton();
        product_list = new javax.swing.JButton();
        Customers = new javax.swing.JButton();
        Employee = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(30, 30, 30));
        jPanel5.setLayout(null);
        getContentPane().add(jPanel5);
        jPanel5.setBounds(1710, 220, 370, 780);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/home_bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 290, 1280, 620);

        jPanel4.setBackground(new java.awt.Color(30, 30, 30));
        jPanel4.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Designed By Team c");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(490, 40, 140, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/teamc.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3);
        jLabel3.setBounds(650, 10, 53, 70);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(450, 910, 1560, 180);

        jPanel1.setBackground(new java.awt.Color(30, 30, 30));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/home.png"))); // NOI18N
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 10, 722, 372);

        jPanel3.setBackground(null);
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.black, java.awt.Color.white, null));
        jPanel3.setLayout(null);

        jdate.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        jdate.setForeground(new java.awt.Color(255, 255, 255));
        jdate.setText("11/02/2022");
        jPanel3.add(jdate);
        jdate.setBounds(110, 70, 160, 40);

        jtime.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        jtime.setForeground(new java.awt.Color(255, 255, 255));
        jtime.setText("10:06:05");
        jPanel3.add(jtime);
        jtime.setBounds(30, 10, 220, 60);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1450, 170, 260, 120);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/BUBT.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel22);
        jLabel22.setBounds(1590, 20, 120, 140);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -10, 2030, 430);

        jPanel2.setBackground(new java.awt.Color(30, 30, 30));
        jPanel2.setLayout(null);

        Purchase.setBackground(new java.awt.Color(0, 0, 0));
        Purchase.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        Purchase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/purchase_1.png"))); // NOI18N
        Purchase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, java.awt.Color.white, null));
        Purchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PurchaseActionPerformed(evt);
            }
        });
        jPanel2.add(Purchase);
        Purchase.setBounds(50, 90, 170, 160);

        product_list.setBackground(new java.awt.Color(0, 0, 0));
        product_list.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        product_list.setForeground(new java.awt.Color(255, 255, 255));
        product_list.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/product.png"))); // NOI18N
        product_list.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, java.awt.Color.white, null));
        product_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                product_listActionPerformed(evt);
            }
        });
        jPanel2.add(product_list);
        product_list.setBounds(280, 90, 170, 160);

        Customers.setBackground(new java.awt.Color(0, 0, 0));
        Customers.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        Customers.setForeground(new java.awt.Color(255, 255, 255));
        Customers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/rsz_customersss.png"))); // NOI18N
        Customers.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, java.awt.Color.white, null));
        Customers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomersActionPerformed(evt);
            }
        });
        jPanel2.add(Customers);
        Customers.setBounds(50, 370, 170, 160);

        Employee.setBackground(new java.awt.Color(0, 0, 0));
        Employee.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        Employee.setForeground(new java.awt.Color(255, 255, 255));
        Employee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/employee_1.png"))); // NOI18N
        Employee.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, java.awt.Color.white, null));
        Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeActionPerformed(evt);
            }
        });
        jPanel2.add(Employee);
        Employee.setBounds(290, 370, 170, 160);

        jLabel5.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Purchase");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 220, 170, 110);

        jLabel6.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Products");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(310, 220, 160, 110);

        jLabel7.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Employee");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(320, 500, 170, 110);

        jLabel8.setFont(new java.awt.Font("Arial", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Customer");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(70, 500, 170, 110);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 350, 570, 720);

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 0));

        jMenu3.setBackground(new java.awt.Color(255, 153, 0));
        jMenu3.setForeground(new java.awt.Color(204, 0, 0));
        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/rsz_1exittttt.png"))); // NOI18N
        jMenu3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeActionPerformed

        employee info = new employee();
        info.setBounds(1, 1, 2000, 1080);
        info.setVisible(true);
         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeActionPerformed

    private void CustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomersActionPerformed
   

        customer info = new customer();
        info.setBounds(1, 1, 2000, 1080);
        info.setVisible(true);    
         dispose();// TODO add your handling code here:
    }//GEN-LAST:event_CustomersActionPerformed

    private void PurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PurchaseActionPerformed

        purchase info = new purchase();
        info.setBounds(1, 1, 2000, 1080);
        info.setVisible(true);  
         dispose();// TODO add your handling code here:
    }//GEN-LAST:event_PurchaseActionPerformed

    private void product_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_product_listActionPerformed
 
        Add_Product info = new Add_Product();
        info.setBounds(1, 1, 2000, 1080);
        info.setVisible(true); 
         dispose();// TODO add your handling code here:
    }//GEN-LAST:event_product_listActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(null, "Are you sure to exit ?", "WARNING", dialogButton);
        if (dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if (dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       
        Group_info info = new Group_info();
        info.setBounds(1, 1, 2000, 1080);
        info.setVisible(true);
         dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked


Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://bubt.edu.bd"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}
//catch(URISyntaxException  err ){


        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Home_Page ob1 = new Home_Page();
                ob1.setBounds(1, 1, 2000, 1080);
                ob1.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Customers;
    private javax.swing.JButton Employee;
    private javax.swing.JButton Purchase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jdate;
    private javax.swing.JLabel jtime;
    private javax.swing.JButton product_list;
    // End of variables declaration//GEN-END:variables
private void systemexit() {
        WindowEvent winClosing = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        setVisible(false);
        dispose();
        System.exit(0);
    }
}
