/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.sun.glass.events.KeyEvent;
import static com.sun.xml.internal.fastinfoset.alphabet.BuiltInRestrictedAlphabets.table;
import java.awt.Desktop;
import java.awt.print.PrinterException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.lang.NumberFormatException;
import java.lang.Integer;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author hp
 */
public class purchase extends javax.swing.JFrame {

    /**
     * Creates new form purchase
     */
    public purchase() {
        initComponents();
     Connect();
      table_load();
      auto_id();
        
    }
    
     Connection con;
PreparedStatement pst;
ResultSet rs;
public void Connect()
    {
        try {
           Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/super_shop", "root","");
        }
        catch (Exception e)
        {
        }
    }
    

   public void table_load()
	    {
	    	try 
	    	{
		    pst = con.prepareStatement("select * from product_details");
		    rs = pst.executeQuery();
		  jTable2.setModel(DbUtils.resultSetToTableModel(rs));
		} 
	    	catch (SQLException e) 
	    	 {
	    		e.printStackTrace();
		  } 
	    }
public void auto_id()
    {
        try {
          
            Statement s = con.createStatement();
            ResultSet rs = s.executeQuery("SELECT MAX(id) FROM customer_details");
            rs.next();
            rs.getString("MAX(id)");
            if (rs.getString("MAX(id)") == null) {
                id.setText("01");    
            } else {
                int c_id = rs.getInt(1);
                c_id++;
              id.setText(Integer.toString( c_id));
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        add_cart = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pcode = new javax.swing.JTextField();
        pquantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        totalprice1 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        totalprice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pprice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tsearch = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/teamc.png"))); // NOI18N
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 880, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Designed By Team c");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 910, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/purchase_1.png"))); // NOI18N
        jLabel1.setText("Purchase");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 340, 80));

        jTable1.setBackground(new java.awt.Color(0, 0, 0));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product code", "Product Name ", "Price ", "quantity", "Total Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 200, 470, 215));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selected products: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 170, 160, 33));

        jTable2.setBackground(new java.awt.Color(0, 0, 0));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Product Code", "Product Name", "Price"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 470, 400));

        add_cart.setBackground(new java.awt.Color(0, 153, 51));
        add_cart.setFont(new java.awt.Font("Arial Black", 1, 20)); // NOI18N
        add_cart.setForeground(new java.awt.Color(255, 255, 255));
        add_cart.setText("Add to cart");
        add_cart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_cartActionPerformed(evt);
            }
        });
        getContentPane().add(add_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 610, 170, 30));

        jLabel4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel4.setText("product code: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 520, -1, 25));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel5.setText("Quantity:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, -1, 25));

        pcode.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pcodeKeyPressed(evt);
            }
        });
        getContentPane().add(pcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, 60, -1));

        pquantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pquantityKeyPressed(evt);
            }
        });
        getContentPane().add(pquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 560, 60, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total Products: ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, 60));

        jButton2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setText("Make Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1660, 470, 130, 30));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Amount:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 430, -1, 25));

        totalprice1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalprice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalprice1ActionPerformed(evt);
            }
        });
        getContentPane().add(totalprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 420, 90, 40));

        bill.setBackground(new java.awt.Color(204, 204, 204));
        bill.setColumns(20);
        bill.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        bill.setRows(5);
        jScrollPane3.setViewportView(bill);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 510, 350, 350));

        jPanel1.setBackground(new java.awt.Color(255, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel12.setText("Customer Info:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(240, 10, 260, 60);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("Full Name :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(310, 100, 100, 20);

        name.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameKeyPressed(evt);
            }
        });
        jPanel1.add(name);
        name.setBounds(420, 91, 210, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Address : ");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(320, 140, 90, 20);

        address.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressKeyPressed(evt);
            }
        });
        jPanel1.add(address);
        address.setBounds(420, 140, 210, 30);

        id.setBackground(new java.awt.Color(51, 51, 51));
        id.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        id.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(id);
        id.setBounds(110, 93, 180, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel13.setText("Id :");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(70, 100, 40, 20);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("Phone No:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 140, 110, 20);

        phone.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                phoneMouseClicked(evt);
            }
        });
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                phoneKeyPressed(evt);
            }
        });
        jPanel1.add(phone);
        phone.setBounds(110, 140, 180, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 640, 180));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(null);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel15.setText("Products Selecting");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(200, 0, 290, 60);

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel6.setText("product name: ");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(220, 100, 127, 25);

        jLabel7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel7.setText("Total Amount:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(220, 140, 120, 25);

        pname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnameActionPerformed(evt);
            }
        });
        jPanel2.add(pname);
        pname.setBounds(350, 100, 160, 30);

        totalprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalpriceActionPerformed(evt);
            }
        });
        jPanel2.add(totalprice);
        totalprice.setBounds(350, 140, 160, 30);

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel3.setText("Price: ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(520, 100, 56, 25);

        pprice.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel2.add(pprice);
        pprice.setBounds(570, 100, 60, 30);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 640, 180));

        jButton1.setBackground(new java.awt.Color(0, 0, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/print.png"))); // NOI18N
        jButton1.setText("print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 880, 110, 50));

        tsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsearchActionPerformed(evt);
            }
        });
        tsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsearchKeyReleased(evt);
            }
        });
        getContentPane().add(tsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 120, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/BUBT.png"))); // NOI18N
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1740, 0, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/search.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/purchase_bg.jpg"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 2230, 1020));

        jMenuBar1.setBackground(new java.awt.Color(255, 153, 0));
        jMenuBar1.setBorder(null);

        jMenu1.setBackground(new java.awt.Color(0, 51, 51));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/home_1.png"))); // NOI18N
        jMenu1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(0, 0, 0));
        jMenu2.setForeground(new java.awt.Color(204, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/rsz_1exittttt.png"))); // NOI18N
        jMenu2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_cartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_cartActionPerformed
   


        DefaultTableModel model = new DefaultTableModel();
       
        model=(DefaultTableModel)jTable1.getModel();
        model.addRow(new Object[]
                
        {
          
            pcode.getText(),
            pname.getText(),
            pprice.getText(),
            pquantity.getText(),
            totalprice.getText(),          
        });  
                
            int sum = 0;
                    
        for(int i = 0; i<jTable1.getRowCount(); i++)
        {
            sum = sum + Integer.parseInt(jTable1.getValueAt(i, 4).toString());
        }
        
   totalprice1.setText(Integer.toString(sum));
          
          pcode.setText("");
         pname.setText("");
           pprice.setText("");
        pquantity.setText("");
        totalprice.setText("");
        
       pcode.requestFocus();
   
        // TODO add your handling code here:
    }//GEN-LAST:event_add_cartActionPerformed
    

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        
String c_id,c_name,c_phone,c_address;
c_id = id.getText();
c_name = name.getText();
c_phone =phone.getText();
c_address=address.getText();
try {
pst = con.prepareStatement("insert into customer_details(id,name,phone_no,address)values(?,?,?,?)");
pst.setString(1, c_id);
pst.setString(2, c_name);
pst.setString(3, c_phone);
pst.setString(4,c_address);
pst.executeUpdate();
   }
 
catch (SQLException e1)
        {
e1.printStackTrace();
}
        String total = totalprice1.getText();
         String jname = name.getText();
         
          DefaultTableModel model = new DefaultTableModel();
        
        model = (DefaultTableModel)jTable1.getModel();
       bill.setText(bill.getText() + "    _______________________\n");
       bill.setText(bill.getText() + "                   Welcome    \n");
        bill.setText(bill.getText() + "    ***   Team C Supershop   ***\n");
         bill.setText(bill.getText() + "    ________________________\n");

          bill.setText(bill.getText() +  "    --------------------------------\n");
                   bill.setText(bill.getText() + "    ________________________\n");
       bill.setText(bill.getText() + "\t" + "Hi, "+ jname+ "\n"+ "Here is your cash memo:"  + "\n"  );
 bill.setText(bill.getText() + "---------------------------\n");
        
         //Heading
          bill.setText(bill.getText() + "Product" + "\t" + "Quantity " + "\t" + "Amount" + "\n"  );
          
       
          
          
     for(int i = 0; i < model.getRowCount(); i++)
          {
              
              String pname = (String)model.getValueAt(i, 1);
              String Quantity = (String)model.getValueAt(i, 3);
              String amount = (String)model.getValueAt(i, 4);
              
           bill.setText(bill.getText() + pname  + "\t" + Quantity + "\t" + amount  + "\n"  );
    
          }
          
          bill.setText(bill.getText() + "\n");    
          
         bill.setText(bill.getText() + "\t"  + "Total Amount :" + total + " tk .\n");
         
      bill.setText(bill.getText() + "\n");
    
          bill.setText(bill.getText() + "        Thank You   " + jname+". \n \t Come Again.      \n");
          
 bill.setText(bill.getText() + "    ________________________\n");
  bill.setText(bill.getText() + "   ************************\n");
 


        
    name.setText("");
     auto_id();
phone.setText("");
address.setText("");
totalprice1.setText("");

name.requestFocus();    

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcodeKeyPressed

 if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String s_code=pcode.getText();
          
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/super_shop","root","");
                pst = con.prepareStatement("select * from product_details where code = ?");
                pst.setString(1, s_code);
                rs = pst.executeQuery();
                
                if(rs.next() == false)
                {    
                    JOptionPane.showMessageDialog(this, "Product Code Not Found");  
                }
                else
                {
                    String name = rs.getString("name");
                     String price = rs.getString("price");
                     pname.setText(name.trim());
                     pprice.setText(price.trim());
                }
            }catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                  java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    

        // TODO add your handling code here:
    }//GEN-LAST:event_pcodeKeyPressed

    private void pquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pquantityKeyPressed


        int quantity = Integer.parseInt(pquantity.getText());
   int price = Integer.parseInt(pprice.getText());
        int total = quantity*price;
        
        totalprice.setText(String.valueOf(total));
        
  
        // TODO add your handling code here:
    }//GEN-LAST:event_pquantityKeyPressed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
 int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog (null, "Are you sure to exit ?","WARNING", dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
            if(dialogButton == JOptionPane.NO_OPTION) {
              remove(dialogButton);
            }  

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

 Home_Page info = new  Home_Page();
  info.setBounds(1,1,2000,1080);
        info.setVisible(true);
         dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void pnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pnameActionPerformed

    private void totalpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalpriceActionPerformed

    private void nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_nameKeyPressed

    private void addressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressKeyPressed
 // TODO add your handling code here:
    }//GEN-LAST:event_addressKeyPressed

    private void phoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_phoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneMouseClicked

    private void phoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyPressed

if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String c_phone=phone.getText();
          
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/super_shop","root","");
                pst = con.prepareStatement("select * from customer_details where phone_no = ?");
                pst.setString(1, c_phone);
                rs = pst.executeQuery();
                
                if(rs.next() == false)
                {    
                    JOptionPane.showMessageDialog(this, "Customer Not Found, Please Register");
                    
        name.setText("");
   
        address.setText("");
       pcode.requestFocus();
                    
                }
                else
                {
                     String c_id = rs.getString("id");
                    String  c_name = rs.getString("name");
                     String c_address = rs.getString("address");
                   id.setText(c_id.trim());
                     name.setText(c_name.trim());
                     address.setText(c_address.trim());
                }
            }catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                  java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    


        // TODO add your handling code here:
    }//GEN-LAST:event_phoneKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

      try
        {
           bill.print();
           bill.setText("");

        }
        catch (PrinterException ex) {
          //  Logger.getLogger(pos.class.getName()).log(Level.SEVERE, null, ex);
        }  

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tsearchActionPerformed

    private void tsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsearchKeyReleased

DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel)jTable2.getModel();
        String search=tsearch.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr= new TableRowSorter<DefaultTableModel > (model);
        jTable2.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(search));
        // TODO add your handling code here:
    }//GEN-LAST:event_tsearchKeyReleased

    private void totalprice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalprice1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalprice1ActionPerformed

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
 
        Group_info  info = new Group_info ();
        info.setBounds(1,1,2000,1080);
        info.setVisible(true);
 dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://bubt.edu.bd"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel20MouseClicked
        
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_cart;
    private javax.swing.JTextField address;
    private javax.swing.JTextArea bill;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pcode;
    private javax.swing.JTextField phone;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pprice;
    private javax.swing.JTextField pquantity;
    private javax.swing.JTextField totalprice;
    private javax.swing.JTextField totalprice1;
    private javax.swing.JTextField tsearch;
    // End of variables declaration//GEN-END:variables

}
