/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class update_products extends javax.swing.JFrame {

    /**
     * Creates new form update_products
     */
    public update_products() {
        initComponents();
   Connect(); }
       
     Connection con;
PreparedStatement pst;
ResultSet rs;
public void Connect()
    {
        try {
           Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/super_shop", "root","");
        }
        catch (Exception e)
        {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pcode = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        company = new javax.swing.JTextField();
        addnew = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel10.setText("Update Products");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 40, 460, 70);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Enter Product code to update : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 170, 420, 35);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product Name : ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 220, 220, 35);

        pcode.setBackground(new java.awt.Color(0, 102, 0));
        pcode.setForeground(new java.awt.Color(255, 255, 255));
        pcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcodeActionPerformed(evt);
            }
        });
        pcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pcodeKeyPressed(evt);
            }
        });
        getContentPane().add(pcode);
        pcode.setBounds(450, 170, 200, 30);
        getContentPane().add(name);
        name.setBounds(450, 220, 200, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 270, 100, 35);
        getContentPane().add(price);
        price.setBounds(450, 270, 200, 30);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company name :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(210, 310, 230, 40);
        getContentPane().add(company);
        company.setBounds(450, 320, 200, 30);

        addnew.setBackground(new java.awt.Color(0, 102, 0));
        addnew.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addnew.setForeground(new java.awt.Color(255, 255, 255));
        addnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/Refresh-icon (1).png"))); // NOI18N
        addnew.setText("Update");
        addnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewActionPerformed(evt);
            }
        });
        getContentPane().add(addnew);
        addnew.setBounds(540, 360, 110, 33);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 710, 440);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcodeActionPerformed

    private void addnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewActionPerformed

        String c_code,c_name,c_price,c_company,c_category;
        c_code= pcode.getText();
        c_name = name.getText();
        c_price =price.getText();
        c_company=company.getText();

       
        try {
   
            pst = con.prepareStatement("update product_details set name = ?, price = ?,comp_name= ? where code = ?");
         
            pst.setString(1, c_name);
            pst.setString(2, c_price);
            pst.setString(3,c_company);
              pst.setString(4, c_code);
            

            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Updated !");
           
            name.setText("");
            price.setText("");
            company.setText("");
            
            name.requestFocus();
        }

        catch (SQLException e1)
        {
            e1.printStackTrace();
        }
  dispose();
 
        // TODO add your handling code here:
    }//GEN-LAST:event_addnewActionPerformed

    private void pcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pcodeKeyPressed
   
        


 if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            String s_code=pcode.getText();
          
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/super_shop","root","");
                pst = con.prepareStatement("select * from product_details where code = ?");
                pst.setString(1, s_code);
                rs = pst.executeQuery();
                
                if(rs.next() == false)
                {    
                    JOptionPane.showMessageDialog(this, "Product Code Not Found");  
                }
                else
                {
                    String pname = rs.getString("name");
                     String pprice = rs.getString("price");
                       String pcompany = rs.getString("comp_name");
                        String pcategory = rs.getString("category");
                     name.setText(pname.trim());
                     price.setText(pprice.trim());
                     company.setText(pcompany.trim());
          
                }
            }catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                  java.util.logging.Logger.getLogger(purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    






// TODO add your handling code here:
    }//GEN-LAST:event_pcodeKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update_products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addnew;
    private javax.swing.JTextField company;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField pcode;
    private javax.swing.JTextField price;
    // End of variables declaration//GEN-END:variables
}
