/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login;

import java.awt.Desktop;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import login.Home_Page;
import login.employee;
/**
 *
 * @author hp
 */
public class user_login extends javax.swing.JFrame {

    /**
     * Creates new form user_login
     */
    public user_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        resetbutton = new javax.swing.JButton();
        loginbutton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 102));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/login_1.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1360, 170, 240, 150);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Please Enter Your Username And Password to login");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1230, 360, 440, 50);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/user.png"))); // NOI18N
        jLabel2.setText("USERNAME : ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(1190, 440, 200, 90);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/lock.png"))); // NOI18N
        jLabel4.setText("PASSWORD : ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(1190, 520, 190, 80);

        jUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(jUsername);
        jUsername.setBounds(1400, 460, 280, 50);

        jPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(jPassword);
        jPassword.setBounds(1400, 540, 280, 50);

        resetbutton.setBackground(new java.awt.Color(0, 51, 51));
        resetbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        resetbutton.setForeground(new java.awt.Color(255, 255, 255));
        resetbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/Refresh-icon (1).png"))); // NOI18N
        resetbutton.setText("Reset");
        resetbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(resetbutton);
        resetbutton.setBounds(1410, 620, 120, 40);

        loginbutton.setBackground(new java.awt.Color(0, 51, 153));
        loginbutton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        loginbutton.setForeground(new java.awt.Color(255, 255, 255));
        loginbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/unlock.png"))); // NOI18N
        loginbutton.setText("login");
        loginbutton.setBorder(new javax.swing.border.MatteBorder(null));
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(loginbutton);
        loginbutton.setBounds(1570, 620, 110, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/BUBT.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1770, 10, 120, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/login bg.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-40, 0, 2080, 1190);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1950, 1110);

        jMenu1.setForeground(new java.awt.Color(204, 0, 51));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login/pics/rsz_1exittttt.png"))); // NOI18N
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed

    }//GEN-LAST:event_jPasswordActionPerformed

    private void resetbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbuttonActionPerformed
        jUsername.setText(null);
        jPassword.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_resetbuttonActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed

        String password = jPassword.getText();
        String username=jUsername.getText();
        if (password.contains("123")  &&   (username.contains("shahadat")))
        {
            jUsername.setText(null);
            jPassword.setText(null);
            systemexit();
 
            Home_Page info = new Home_Page();
            info.setBounds(1,1,2000,1080);
            info.setVisible(true);
             dispose();
        }
        else if(password.contains("1111")  &&   (username.contains("swt")))
        {
            jUsername.setText(null);
            jPassword.setText(null);
            systemexit();
   
            Home_Page info = new Home_Page();
            info.setBounds(1,1,2000,1080);
            info.setVisible(true);
             dispose();
        }
        else if(password.contains("522")  &&   (username.contains("othu")))
        {
            jUsername.setText(null);
            jPassword.setText(null);
            systemexit();

            Home_Page info = new Home_Page();
            info.setBounds(1,1,2000,1080);
            info.setVisible(true);
             dispose();
        }

        else if(password.contains("048")  &&   (username.contains("shakil")))
        {
            jUsername.setText(null);
            jPassword.setText(null);
            systemexit();

            Home_Page info = new Home_Page();
            info.setBounds(1,1,2000,1080);
            info.setVisible(true);
             dispose();
        }

        else {
            JOptionPane.showMessageDialog(null,"Invaild password or Username","Login error",JOptionPane.ERROR_MESSAGE);
            jUsername.setText(null);
            jPassword.setText(null);

        }

    }//GEN-LAST:event_loginbuttonActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked

  int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog (null, "Are you sure to exit ?","WARNING", dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        if(dialogButton == JOptionPane.NO_OPTION) {
            remove(dialogButton);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
Desktop browser=Desktop.getDesktop();
try{
    try {
        browser.browse(new URI("https://bubt.edu.bd"));
    } catch (URISyntaxException ex) {
        Logger.getLogger(Home_Page.class.getName()).log(Level.SEVERE, null, ex);
    }

}
catch(IOException err)
{}        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(user_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new user_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton resetbutton;
    // End of variables declaration//GEN-END:variables
private void systemexit(){
WindowEvent winClosing = new WindowEvent (this,WindowEvent.WINDOW_CLOSING );
}
}
